CREATE TABLE IF NOT EXISTS admin_users (id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products (id SERIAL PRIMARY KEY, name TEXT NOT NULL, ar TEXT NOT NULL, cat TEXT NOT NULL, price NUMERIC(12,2) NOT NULL, desc_text TEXT DEFAULT '', type TEXT DEFAULT 'bottle', tag TEXT DEFAULT '', stock INTEGER NOT NULL DEFAULT 0, image TEXT DEFAULT '', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, customer_name TEXT NOT NULL, phone TEXT NOT NULL, email TEXT DEFAULT '', city TEXT NOT NULL, address TEXT NOT NULL, note TEXT DEFAULT '', total NUMERIC(12,2) NOT NULL, status TEXT NOT NULL DEFAULT 'جديد', items JSONB NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_orders_phone ON orders(phone);
