const express=require('express');const path=require('path');const fs=require('fs');const {Pool}=require('pg');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const app=express();app.use(express.json({limit:'12mb'}));app.use(express.urlencoded({extended:true,limit:'12mb'}));
const PORT=process.env.PORT||3000;const DATABASE_URL=process.env.DATABASE_URL;const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET';
if(!DATABASE_URL){console.warn('DATABASE_URL غير مضبوط. شغّل الخادم مع رابط PostgreSQL.');}
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
const q=async(text,params=[])=>{if(!pool)throw new Error('قاعدة البيانات غير متصلة');return pool.query(text,params)};
async function init(){if(!pool)return;const schema=fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8');await q(schema);const admin=await q('SELECT id FROM admin_users LIMIT 1');if(!admin.rowCount){const hash=await bcrypt.hash(process.env.ADMIN_PASSWORD||'verse2026',12);await q('INSERT INTO admin_users(username,password_hash) VALUES($1,$2)',[process.env.ADMIN_USER||'admin',hash]);}
const count=await q('SELECT count(*) FROM products');if(Number(count.rows[0].count)===0){const seed=[['Velvet Lipstick','أحمر شفاه Velvet','مكياج',24,'لون غني بلمسة مخملية وثبات أنيق.','bottle','الأكثر مبيعاً',20],['Golden Glow Serum','سيروم Golden Glow','عناية',39,'سيروم خفيف لإطلالة مشرقة وترطيب يومي.','bottle','جديد',15],['Élégance Rose','عطر Élégance Rose','عطور',65,'نفحات وردية فاخرة بلمسة دافئة.','bottle','حصري',10],['Royal Hair Mask','ماسك Royal للشعر','شعر',32,'عناية عميقة تمنح الشعر نعومة وحيوية.','cream','',18]];for(const p of seed)await q('INSERT INTO products(name,ar,cat,price,desc_text,type,tag,stock) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',p);}
const defaults={whatsapp:'15551234567',shippingText:'شحن مجاني للطلبات التي تتجاوز 100$ • مرحباً بكم في Verse Beauty',about:'متجر متخصص في منتجات الجمال والعناية، بهوية فاخرة وتجربة عصرية.',contact:'السبت – الخميس\n9:00 ص – 6:00 م\ninfo@versebeauty.com',goldColor:'#d6a33a'};for(const [k,v] of Object.entries(defaults))await q('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO NOTHING',[k,v]);}
function auth(req,res,next){try{const h=req.headers.authorization||'';const token=h.startsWith('Bearer ')?h.slice(7):'';req.user=jwt.verify(token,JWT_SECRET);next()}catch(e){res.status(401).json({error:'غير مصرح'})}}
app.post('/api/auth/login',async(req,res)=>{try{const {username,password}=req.body;const r=await q('SELECT * FROM admin_users WHERE username=$1',[username||'admin']);if(!r.rowCount||!(await bcrypt.compare(password||'',r.rows[0].password_hash)))return res.status(401).json({error:'بيانات الدخول غير صحيحة'});res.json({token:jwt.sign({id:r.rows[0].id,username:r.rows[0].username},JWT_SECRET,{expiresIn:'7d'})})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/products',async(req,res)=>{try{const r=await q('SELECT id,name,ar,cat,price::float AS price,desc_text AS desc,type,tag,stock,image FROM products ORDER BY id DESC');res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/products',auth,async(req,res)=>{try{const p=req.body;const r=await q('INSERT INTO products(name,ar,cat,price,desc_text,type,tag,stock,image) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,name,ar,cat,price::float AS price,desc_text AS desc,type,tag,stock,image',[p.name,p.ar,p.cat,Number(p.price),p.desc||'',p.type||'bottle',p.tag||'',Number(p.stock)||0,p.image||'']);res.status(201).json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/products/:id',auth,async(req,res)=>{try{const p=req.body;const r=await q('UPDATE products SET name=$1,ar=$2,cat=$3,price=$4,desc_text=$5,type=$6,tag=$7,stock=$8,image=$9,updated_at=now() WHERE id=$10 RETURNING id,name,ar,cat,price::float AS price,desc_text AS desc,type,tag,stock,image',[p.name,p.ar,p.cat,Number(p.price),p.desc||'',p.type||'bottle',p.tag||'',Number(p.stock)||0,p.image||'',req.params.id]);if(!r.rowCount)return res.status(404).json({error:'المنتج غير موجود'});res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/products/:id',auth,async(req,res)=>{try{await q('DELETE FROM products WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/settings',async(req,res)=>{try{const r=await q('SELECT key,value FROM settings');res.json(Object.fromEntries(r.rows.map(x=>[x.key,x.value])))}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/settings',auth,async(req,res)=>{try{for(const [k,v] of Object.entries(req.body||{}))await q('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,String(v)]);if(req.body.newpass){const hash=await bcrypt.hash(req.body.newpass,12);await q('UPDATE admin_users SET password_hash=$1 WHERE id=$2',[hash,req.user.id]);}res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/orders',async(req,res)=>{try{const x=req.body;if(!x.name||!x.phone||!x.city||!x.address||!Array.isArray(x.items)||!x.items.length)return res.status(400).json({error:'بيانات الطلب ناقصة'});const ids=x.items.map(i=>i.id);const r=await q('SELECT id,ar,price::float AS price,stock FROM products WHERE id=ANY($1::int[])',[ids]);const by=new Map(r.rows.map(p=>[p.id,p]));let total=0;const items=[];for(const i of x.items){const p=by.get(Number(i.id));const qty=Math.max(1,Number(i.qty)||1);if(!p||p.stock<qty)return res.status(400).json({error:'أحد المنتجات غير متوفر بالكمية المطلوبة'});total+=p.price*qty;items.push({id:p.id,name:p.ar,qty,price:p.price});}const id='V'+Date.now();await q('BEGIN');try{await q('INSERT INTO orders(id,customer_name,phone,email,city,address,note,total,status,items) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,x.name,x.phone,x.email||'',x.city,x.address,x.note||'',total,'جديد',JSON.stringify(items)]);for(const i of items)await q('UPDATE products SET stock=stock-$1,updated_at=now() WHERE id=$2',[i.qty,i.id]);await q('COMMIT')}catch(e){await q('ROLLBACK');throw e}res.status(201).json({id,total,items})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/orders',auth,async(req,res)=>{try{const r=await q("SELECT id,customer_name AS name,phone,email,city,address,note,total::float AS total,status,items,to_char(created_at,'YYYY-MM-DD HH24:MI') AS date FROM orders ORDER BY created_at DESC");res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.patch('/api/orders/:id',auth,async(req,res)=>{try{const r=await q('UPDATE orders SET status=$1 WHERE id=$2 RETURNING id,status',[req.body.status,req.params.id]);res.json(r.rows[0]||{})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/orders/:id',auth,async(req,res)=>{try{await q('DELETE FROM orders WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.use(express.static(__dirname));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'start.html')));
init().then(()=>app.listen(PORT,()=>console.log(`Verse Beauty running on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
